judgeclient: json_reader.cpp json_value.cpp json_writer.cpp judgeclient.cpp judger.cpp
	g++ json_reader.cpp json_value.cpp json_writer.cpp judgeclient.cpp judger.cpp -Wall -D_GLIBCXX_DEBUG -g -o judgeclient

